# Generated by Django 5.0.1 on 2024-01-31 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_description_task_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 31, 11, 47, 42, 535697, tzinfo=datetime.timezone.utc)),
        ),
    ]
