# Generated by Django 5.0.1 on 2024-02-01 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title_tag',
            field=models.CharField(default='My Tasks', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 1, 11, 50, 46, 599675, tzinfo=datetime.timezone.utc)),
        ),
    ]
