# Generated by Django 5.0.1 on 2024-02-11 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_category_task_category_alter_task_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='likes',
            field=models.ManyToManyField(related_name='task_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
