# Generated by Django 5.0.1 on 2024-02-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='snippet',
            field=models.CharField(default='Click on the link above to add a task.', max_length=200),
        ),
    ]
