# Generated by Django 5.0.1 on 2024-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='snippet',
            field=models.CharField(max_length=200),
        ),
    ]
