# Generated by Django 5.0.1 on 2024-02-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
