# Generated by Django 5.0.1 on 2024-02-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_task_task_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='image_header/'),
        ),
    ]
