# Generated by Django 5.0.1 on 2024-04-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='progress',
        ),
    ]
