# Generated by Django 5.0.1 on 2024-05-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_task_subtask10_text_task_subtask1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask10_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask1_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask2_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask3_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask4_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask5_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask6_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask7_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask8_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask9_text',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask_text',
            field=models.JSONField(default=list),
        ),
    ]
