# Generated by Django 5.0.1 on 2024-05-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_remove_task_subtask10_text_remove_task_subtask1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask_text',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask10_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask1_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask2_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask3_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask4_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask5_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask6_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask7_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask8_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask9_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
