# Generated by Django 5.0.1 on 2024-05-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_remove_task_subtask_text_task_subtask10_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtask10_text',
            new_name='subtask_text_1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask1_text',
            new_name='subtask_text_10',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask2_text',
            new_name='subtask_text_2',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask3_text',
            new_name='subtask_text_3',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask4_text',
            new_name='subtask_text_4',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask5_text',
            new_name='subtask_text_5',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask6_text',
            new_name='subtask_text_6',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask7_text',
            new_name='subtask_text_7',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask8_text',
            new_name='subtask_text_8',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask9_text',
            new_name='subtask_text_9',
        ),
    ]
