# Generated by Django 5.0.1 on 2024-05-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='uncategorized', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='task.category'),
        ),
    ]
