# Generated by Django 5.0.1 on 2024-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default='uncategorized', max_length=200),
        ),
    ]
