# Generated by Django 5.0.1 on 2024-05-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_alter_task_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
