# Generated by Django 5.0.1 on 2024-05-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='likes',
        ),
    ]
