# Generated by Django 5.0.1 on 2024-05-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_remove_task_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
